apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "220"
  namespace: tools
  name: argocd-workaround993-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]