apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "230"
  name: argocd-workaround993-rolebinding
  namespace: tools
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
roleRef:
  kind: Role 
  name: argocd-workaround993-role
  apiGroup: rbac.authorization.k8s.io
